baseURL = "/"
languageCode = "en"
DefaultContentLanguage = "en"
title = "Waseem Medhat's Personal Website and Blog"
theme = "anatole"
summarylength = 10
enableEmoji = true
enableRobotsTXT = true

# Enable Disqus
#disqusShortname = ""

# Google Analytics
#googleAnalytics = "UA-123-45"

pygmentsUseClasses = true
pygmentsCodefences = true
pygmentsStyle = "native"
useHLJS = false

[params]
title = "Waseem Medhat"
author = "Waseem Medhat"
description = "Biostatistics - Visualization - Programming"
profilePicture = "images/r-logo.svg"
keywords = ""
favicon = "favicons/"
customCss = ["css/custom.css", "css/syntax.css"]
mainSections = ["post"]
#images = ["images/site-feature-image.png"]

## Math settings
[params.math]
enable = false  # options: true, false. Enable math support globally, default: false. You can always enable math on per page.
use = "katex"  # options: "katex", "mathjax". default is "katex".

## Social links

[[params.socialIcons]]
icon = "fa-facebook"
title = "Facebook"
url = "https://www.facebook.com/waseem.medhat.gaber"

[[params.socialIcons]]
icon = "fa-linkedin"
title = "Linkedin"
url = "https://www.linkedin.com/in/waseem-medhat/"

[[params.socialIcons]]
icon = "fa-github"
title = "GitHub"
url = "https://github.com/waseem-medhat"

[[params.socialIcons]]
icon = "fa-user"
title = "e-mail"
url = "/about/"

## Menu items

[menu]

  [[menu.main]]
  name = "Home"
  identifier = "home"
  weight = 100
  url = "/"

  [[menu.main]]
  name = "Projects"
  weight = 200
  identifier = "projects"
  url = "/categories/Projects"

  [[menu.main]]
  name = "Tutorials"
  weight = 300
  identifier = "tutorials"
  url = "/categories/Tutorials"

  [[menu.main]]
  name = "Blog"
  weight = 400
  identifier = "blog"
  url = "/categories/Blog"

  [[menu.main]]
  name = "Tags"
  weight = 500
  identifier = "tags"
  url = "/tags/"

  [[menu.main]]
  name = "About"
  weight = 600
  identifier = "about"
  url = "/about/"
